# Generated by Django 4.1.13 on 2023-12-25 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("thumbnail", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("thumbnail", models.URLField()),
                ("track", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=30)),
                ("lastName", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=20, unique=True)),
                (
                    "likedPlaylists",
                    models.ManyToManyField(
                        related_name="liked_users", to="logic.playlist"
                    ),
                ),
                (
                    "likedSongs",
                    models.ManyToManyField(related_name="liked_users", to="logic.song"),
                ),
                (
                    "subscribedArtists",
                    models.ManyToManyField(related_name="subscribers", to="logic.user"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="logic.user",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="collaborators",
            field=models.ManyToManyField(
                related_name="collaborator_playlists", to="logic.user"
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playlists",
                to="logic.user",
            ),
        ),
        migrations.AddField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(related_name="playlists", to="logic.song"),
        ),
    ]
