# Generated by Django 4.1.13 on 2023-12-25 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="user",
            name="likedPlaylists",
        ),
        migrations.RemoveField(
            model_name="user",
            name="likedSongs",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscribedArtists",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
        migrations.DeleteModel(
            name="Song",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
