# Generated by Django 4.1.13 on 2023-12-25 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logic", "0004_user_subscribedartists_song_playlist_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="likedPlaylists",
        ),
        migrations.RemoveField(
            model_name="user",
            name="likedSongs",
        ),
        migrations.RemoveField(
            model_name="user",
            name="subscribedArtists",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
        migrations.DeleteModel(
            name="Song",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
