# Generated by Django 4.1.13 on 2023-12-25 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logic", "0006_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="collaborators",
            field=models.ManyToManyField(
                null=True,
                related_name="collaborator_playlists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="songs",
            field=models.ManyToManyField(
                null=True, related_name="playlists", to="logic.song"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="likedPlaylists",
            field=models.ManyToManyField(
                null=True, related_name="liked_users", to="logic.playlist"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="subscribedArtists",
            field=models.ManyToManyField(
                null=True, related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
